FROM python:3.11

WORKDIR /test_frame

COPY test_frame/requirements.txt .

RUN pip install --upgrade pip && pip install -r requirements.txt

COPY test_frame/ .

ENV PYTHONPATH=/test_frame

WORKDIR /test_frame

CMD ["pytest", "tests", "--alluredir=allure-results"]